/* This file was automatically generated by pyNLControl.*/


#include "UKF_Code.h"

void UKF_Code_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xp, casadi_real *Pp, casadi_real *Q11, casadi_real *Q22, casadi_real *Q33, casadi_real *Q44, casadi_real *Q55, casadi_real *R, casadi_real *xhat,  casadi_real *Phat );