/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) EKF_Code_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};

/* EKF_Func:(u,y,xhatp[5],Pkp[5x5],Q11,Q22,Q33,Q44,Q55,R)->(xhat[5],Phat[5x5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[2]? arg[2][0] : 0;
  a1=3.3333333333333335e-003;
  a2=arg[2]? arg[2][1] : 0;
  a3=2.;
  a4=1.0000000000000000e-002;
  a5=arg[2]? arg[2][2] : 0;
  a6=(a4*a5);
  a6=(a2+a6);
  a7=(a3*a6);
  a7=(a2+a7);
  a8=-2.;
  a9=2.0000000000000001e-001;
  a10=arg[2]? arg[2][3] : 0;
  a11=(a9*a10);
  a12=(a8/a11);
  a13=(a12*a0);
  a14=arg[2]? arg[2][4] : 0;
  a15=(a9*a10);
  a16=(a14/a15);
  a17=5.0000000000000003e-002;
  a18=(a17*a10);
  a18=(a9*a18);
  a19=(1./a18);
  a20=(a16+a19);
  a21=(a20*a2);
  a13=(a13-a21);
  a21=(a14/a10);
  a22=5.;
  a23=(a21+a22);
  a24=(a23*a5);
  a13=(a13-a24);
  a24=arg[0]? arg[0][0] : 0;
  a25=(a9*a10);
  a26=(a24/a25);
  a13=(a13-a26);
  a27=(a4*a13);
  a27=(a5+a27);
  a28=(a4*a27);
  a28=(a2+a28);
  a29=(a3*a28);
  a7=(a7+a29);
  a29=2.0000000000000000e-002;
  a30=(a9*a10);
  a31=(a8/a30);
  a32=(a4*a2);
  a32=(a0+a32);
  a33=(a31*a32);
  a34=(a9*a10);
  a35=(a14/a34);
  a36=(a17*a10);
  a36=(a9*a36);
  a37=(1./a36);
  a38=(a35+a37);
  a39=(a38*a6);
  a33=(a33-a39);
  a39=(a14/a10);
  a40=(a39+a22);
  a41=(a40*a27);
  a33=(a33-a41);
  a41=(a9*a10);
  a42=(a24/a41);
  a33=(a33-a42);
  a43=(a4*a33);
  a43=(a5+a43);
  a44=(a29*a43);
  a44=(a2+a44);
  a7=(a7+a44);
  a7=(a1*a7);
  a7=(a0+a7);
  a45=1.;
  a46=(a4*a12);
  a47=(a4*a46);
  a48=(a3*a47);
  a49=(a40*a46);
  a49=(a31-a49);
  a50=(a4*a49);
  a51=(a29*a50);
  a48=(a48+a51);
  a48=(a1*a48);
  a48=(a45+a48);
  a52=arg[3]? arg[3][0] : 0;
  a53=(a48*a52);
  a54=3.;
  a55=(a4*a20);
  a56=(a4*a55);
  a56=(a45-a56);
  a57=(a3*a56);
  a54=(a54+a57);
  a57=(a4*a31);
  a57=(a57-a38);
  a58=(a40*a55);
  a57=(a57+a58);
  a58=(a4*a57);
  a59=(a29*a58);
  a59=(a45+a59);
  a54=(a54+a59);
  a54=(a1*a54);
  a60=arg[3]? arg[3][1] : 0;
  a61=(a54*a60);
  a53=(a53+a61);
  a61=(a4*a23);
  a61=(a45-a61);
  a62=(a4*a61);
  a63=(a3*a62);
  a63=(a29+a63);
  a38=(a4*a38);
  a64=(a40*a61);
  a38=(a38+a64);
  a64=(a4*a38);
  a64=(a45-a64);
  a65=(a29*a64);
  a63=(a63+a65);
  a63=(a1*a63);
  a66=arg[3]? arg[3][2] : 0;
  a67=(a63*a66);
  a53=(a53+a67);
  a16=(a16/a15);
  a16=(a9*a16);
  a67=1.0000000000000002e-002;
  a19=(a19/a18);
  a19=(a67*a19);
  a16=(a16+a19);
  a16=(a2*a16);
  a11=(a12/a11);
  a11=(a9*a11);
  a11=(a0*a11);
  a16=(a16-a11);
  a21=(a21/a10);
  a21=(a5*a21);
  a16=(a16+a21);
  a26=(a26/a25);
  a26=(a9*a26);
  a16=(a16+a26);
  a26=(a4*a16);
  a25=(a4*a26);
  a21=(a3*a25);
  a35=(a35/a34);
  a35=(a9*a35);
  a37=(a37/a36);
  a37=(a67*a37);
  a35=(a35+a37);
  a35=(a6*a35);
  a31=(a31/a30);
  a31=(a9*a31);
  a32=(a32*a31);
  a35=(a35-a32);
  a32=(a40*a26);
  a39=(a39/a10);
  a39=(a27*a39);
  a32=(a32-a39);
  a35=(a35-a32);
  a42=(a42/a41);
  a42=(a9*a42);
  a35=(a35+a42);
  a42=(a4*a35);
  a41=(a29*a42);
  a21=(a21+a41);
  a21=(a1*a21);
  a32=arg[3]? arg[3][3] : 0;
  a39=(a21*a32);
  a53=(a53+a39);
  a15=(a2/a15);
  a39=(a5/a10);
  a15=(a15+a39);
  a39=(a4*a15);
  a31=(a4*a39);
  a30=(a3*a31);
  a34=(a6/a34);
  a37=(a27/a10);
  a40=(a40*a39);
  a37=(a37-a40);
  a34=(a34+a37);
  a37=(a4*a34);
  a40=(a29*a37);
  a30=(a30+a40);
  a30=(a1*a30);
  a36=arg[3]? arg[3][4] : 0;
  a11=(a30*a36);
  a53=(a53-a11);
  a46=(a3*a46);
  a11=(a3*a50);
  a46=(a46+a11);
  a11=(a9*a10);
  a19=(a8/a11);
  a18=(a9*a10);
  a68=(a14/a18);
  a69=(a17*a10);
  a69=(a9*a69);
  a70=(1./a69);
  a71=(a68+a70);
  a72=(a71*a47);
  a72=(a19-a72);
  a73=(a14/a10);
  a74=(a73+a22);
  a50=(a74*a50);
  a72=(a72-a50);
  a50=(a29*a72);
  a46=(a46+a50);
  a46=(a1*a46);
  a75=(a53*a46);
  a76=arg[3]? arg[3][5] : 0;
  a77=(a48*a76);
  a78=arg[3]? arg[3][6] : 0;
  a79=(a54*a78);
  a77=(a77+a79);
  a79=arg[3]? arg[3][7] : 0;
  a80=(a63*a79);
  a77=(a77+a80);
  a80=arg[3]? arg[3][8] : 0;
  a81=(a21*a80);
  a77=(a77+a81);
  a81=arg[3]? arg[3][9] : 0;
  a82=(a30*a81);
  a77=(a77-a82);
  a82=(a3*a58);
  a55=(a3*a55);
  a82=(a82-a55);
  a55=(a4*a19);
  a83=(a71*a56);
  a55=(a55-a83);
  a58=(a74*a58);
  a55=(a55-a58);
  a58=(a29*a55);
  a82=(a82+a58);
  a82=(a1*a82);
  a82=(a45+a82);
  a83=(a77*a82);
  a75=(a75+a83);
  a83=arg[3]? arg[3][10] : 0;
  a84=(a48*a83);
  a85=arg[3]? arg[3][11] : 0;
  a86=(a54*a85);
  a84=(a84+a86);
  a86=arg[3]? arg[3][12] : 0;
  a87=(a63*a86);
  a84=(a84+a87);
  a87=arg[3]? arg[3][13] : 0;
  a88=(a21*a87);
  a84=(a84+a88);
  a88=arg[3]? arg[3][14] : 0;
  a89=(a30*a88);
  a84=(a84-a89);
  a61=(a3*a61);
  a61=(a45+a61);
  a89=(a3*a64);
  a61=(a61+a89);
  a89=1.0000000000000000e-004;
  a89=(a89*a19);
  a90=(a71*a62);
  a89=(a89-a90);
  a64=(a74*a64);
  a89=(a89-a64);
  a64=(a29*a89);
  a64=(a45+a64);
  a61=(a61+a64);
  a61=(a1*a61);
  a90=(a84*a61);
  a75=(a75+a90);
  a90=arg[3]? arg[3][15] : 0;
  a91=(a48*a90);
  a92=arg[3]? arg[3][16] : 0;
  a93=(a54*a92);
  a91=(a91+a93);
  a93=arg[3]? arg[3][17] : 0;
  a94=(a63*a93);
  a91=(a91+a94);
  a94=arg[3]? arg[3][18] : 0;
  a95=(a21*a94);
  a91=(a91+a95);
  a95=arg[3]? arg[3][19] : 0;
  a96=(a30*a95);
  a91=(a91-a96);
  a26=(a3*a26);
  a96=(a3*a42);
  a26=(a26+a96);
  a96=(a9*a10);
  a97=(a24/a96);
  a96=(a97/a96);
  a96=(a9*a96);
  a4=(a4*a6);
  a4=(a0+a4);
  a11=(a19/a11);
  a11=(a9*a11);
  a11=(a4*a11);
  a6=(a71*a25);
  a68=(a68/a18);
  a68=(a9*a68);
  a70=(a70/a69);
  a70=(a67*a70);
  a68=(a68+a70);
  a68=(a28*a68);
  a6=(a6-a68);
  a11=(a11+a6);
  a42=(a74*a42);
  a73=(a73/a10);
  a73=(a43*a73);
  a42=(a42-a73);
  a11=(a11+a42);
  a96=(a96-a11);
  a11=(a29*a96);
  a26=(a26+a11);
  a26=(a1*a26);
  a42=(a91*a26);
  a75=(a75+a42);
  a42=arg[3]? arg[3][20] : 0;
  a73=(a48*a42);
  a6=arg[3]? arg[3][21] : 0;
  a68=(a54*a6);
  a73=(a73+a68);
  a68=arg[3]? arg[3][22] : 0;
  a70=(a63*a68);
  a73=(a73+a70);
  a70=arg[3]? arg[3][23] : 0;
  a69=(a21*a70);
  a73=(a73+a69);
  a69=arg[3]? arg[3][24] : 0;
  a98=(a30*a69);
  a73=(a73-a98);
  a39=(a3*a39);
  a98=(a3*a37);
  a39=(a39+a98);
  a18=(a28/a18);
  a98=(a71*a31);
  a18=(a18-a98);
  a98=(a43/a10);
  a37=(a74*a37);
  a98=(a98-a37);
  a18=(a18+a98);
  a98=(a29*a18);
  a39=(a39+a98);
  a39=(a1*a39);
  a37=(a73*a39);
  a75=(a75-a37);
  a37=(a46*a52);
  a99=(a82*a60);
  a37=(a37+a99);
  a99=(a61*a66);
  a37=(a37+a99);
  a99=(a26*a32);
  a37=(a37+a99);
  a99=(a39*a36);
  a37=(a37-a99);
  a99=(a37*a46);
  a100=(a46*a76);
  a101=(a82*a78);
  a100=(a100+a101);
  a101=(a61*a79);
  a100=(a100+a101);
  a101=(a26*a80);
  a100=(a100+a101);
  a101=(a39*a81);
  a100=(a100-a101);
  a101=(a100*a82);
  a99=(a99+a101);
  a101=(a46*a83);
  a102=(a82*a85);
  a101=(a101+a102);
  a102=(a61*a86);
  a101=(a101+a102);
  a102=(a26*a87);
  a101=(a101+a102);
  a102=(a39*a88);
  a101=(a101-a102);
  a102=(a101*a61);
  a99=(a99+a102);
  a102=(a46*a90);
  a103=(a82*a92);
  a102=(a102+a103);
  a103=(a61*a93);
  a102=(a102+a103);
  a103=(a26*a94);
  a102=(a102+a103);
  a103=(a39*a95);
  a102=(a102-a103);
  a103=(a102*a26);
  a99=(a99+a103);
  a103=(a46*a42);
  a104=(a82*a6);
  a103=(a103+a104);
  a104=(a61*a68);
  a103=(a103+a104);
  a104=(a26*a70);
  a103=(a103+a104);
  a104=(a39*a69);
  a103=(a103-a104);
  a104=(a103*a39);
  a99=(a99-a104);
  a104=arg[5]? arg[5][0] : 0;
  a99=(a99+a104);
  a104=arg[9]? arg[9][0] : 0;
  a104=(a99+a104);
  a105=(a75/a104);
  a106=arg[1]? arg[1][0] : 0;
  a27=(a3*a27);
  a27=(a5+a27);
  a107=(a3*a43);
  a27=(a27+a107);
  a19=(a19*a4);
  a71=(a71*a28);
  a19=(a19-a71);
  a74=(a74*a43);
  a19=(a19-a74);
  a19=(a19-a97);
  a97=(a29*a19);
  a97=(a5+a97);
  a27=(a27+a97);
  a27=(a1*a27);
  a2=(a2+a27);
  a106=(a106-a2);
  a27=(a105*a106);
  a7=(a7+a27);
  if (res[0]!=0) res[0][0]=a7;
  a7=(a99/a104);
  a27=(a7*a106);
  a2=(a2+a27);
  if (res[0]!=0) res[0][1]=a2;
  a33=(a3*a33);
  a13=(a13+a33);
  a19=(a3*a19);
  a13=(a13+a19);
  a19=(a9*a10);
  a8=(a8/a19);
  a28=(a29*a28);
  a0=(a0+a28);
  a28=(a8*a0);
  a33=(a9*a10);
  a2=(a14/a33);
  a17=(a17*a10);
  a17=(a9*a17);
  a27=(1./a17);
  a74=(a2+a27);
  a43=(a74*a44);
  a28=(a28-a43);
  a43=(a14/a10);
  a22=(a43+a22);
  a71=(a22*a97);
  a28=(a28-a71);
  a71=(a9*a10);
  a24=(a24/a71);
  a28=(a28-a24);
  a13=(a13+a28);
  a13=(a1*a13);
  a5=(a5+a13);
  a49=(a3*a49);
  a12=(a12+a49);
  a72=(a3*a72);
  a12=(a12+a72);
  a47=(a29*a47);
  a47=(a45+a47);
  a47=(a8*a47);
  a51=(a74*a51);
  a47=(a47-a51);
  a50=(a22*a50);
  a47=(a47-a50);
  a12=(a12+a47);
  a12=(a1*a12);
  a52=(a12*a52);
  a57=(a3*a57);
  a57=(a57-a20);
  a55=(a3*a55);
  a57=(a57+a55);
  a56=(a29*a56);
  a56=(a8*a56);
  a59=(a74*a59);
  a56=(a56-a59);
  a58=(a22*a58);
  a56=(a56-a58);
  a57=(a57+a56);
  a57=(a1*a57);
  a60=(a57*a60);
  a52=(a52+a60);
  a89=(a3*a89);
  a38=(a3*a38);
  a23=(a23+a38);
  a89=(a89-a23);
  a62=(a29*a62);
  a62=(a8*a62);
  a65=(a74*a65);
  a62=(a62-a65);
  a64=(a22*a64);
  a62=(a62-a64);
  a89=(a89+a62);
  a89=(a1*a89);
  a89=(a45+a89);
  a66=(a89*a66);
  a52=(a52+a66);
  a35=(a3*a35);
  a16=(a16+a35);
  a96=(a3*a96);
  a16=(a16+a96);
  a25=(a29*a25);
  a25=(a8*a25);
  a19=(a8/a19);
  a19=(a9*a19);
  a0=(a0*a19);
  a25=(a25-a0);
  a41=(a74*a41);
  a2=(a2/a33);
  a2=(a9*a2);
  a27=(a27/a17);
  a67=(a67*a27);
  a2=(a2+a67);
  a2=(a44*a2);
  a41=(a41-a2);
  a25=(a25-a41);
  a11=(a22*a11);
  a43=(a43/a10);
  a43=(a97*a43);
  a11=(a11-a43);
  a25=(a25-a11);
  a24=(a24/a71);
  a9=(a9*a24);
  a25=(a25+a9);
  a16=(a16+a25);
  a16=(a1*a16);
  a25=(a16*a32);
  a52=(a52+a25);
  a34=(a3*a34);
  a15=(a15+a34);
  a3=(a3*a18);
  a15=(a15+a3);
  a29=(a29*a31);
  a8=(a8*a29);
  a44=(a44/a33);
  a74=(a74*a40);
  a44=(a44-a74);
  a8=(a8+a44);
  a97=(a97/a10);
  a22=(a22*a98);
  a97=(a97-a22);
  a8=(a8+a97);
  a15=(a15+a8);
  a1=(a1*a15);
  a15=(a1*a36);
  a52=(a52-a15);
  a15=(a52*a46);
  a76=(a12*a76);
  a78=(a57*a78);
  a76=(a76+a78);
  a79=(a89*a79);
  a76=(a76+a79);
  a79=(a16*a80);
  a76=(a76+a79);
  a79=(a1*a81);
  a76=(a76-a79);
  a79=(a76*a82);
  a15=(a15+a79);
  a83=(a12*a83);
  a85=(a57*a85);
  a83=(a83+a85);
  a86=(a89*a86);
  a83=(a83+a86);
  a86=(a16*a87);
  a83=(a83+a86);
  a86=(a1*a88);
  a83=(a83-a86);
  a86=(a83*a61);
  a15=(a15+a86);
  a90=(a12*a90);
  a92=(a57*a92);
  a90=(a90+a92);
  a93=(a89*a93);
  a90=(a90+a93);
  a93=(a16*a94);
  a90=(a90+a93);
  a93=(a1*a95);
  a90=(a90-a93);
  a93=(a90*a26);
  a15=(a15+a93);
  a42=(a12*a42);
  a6=(a57*a6);
  a42=(a42+a6);
  a68=(a89*a68);
  a42=(a42+a68);
  a68=(a16*a70);
  a42=(a42+a68);
  a68=(a1*a69);
  a42=(a42-a68);
  a68=(a42*a39);
  a15=(a15-a68);
  a68=(a15/a104);
  a6=(a68*a106);
  a5=(a5+a6);
  if (res[0]!=0) res[0][2]=a5;
  a5=(a32*a46);
  a6=(a80*a82);
  a5=(a5+a6);
  a6=(a87*a61);
  a5=(a5+a6);
  a6=(a94*a26);
  a5=(a5+a6);
  a6=(a70*a39);
  a5=(a5-a6);
  a6=(a5/a104);
  a93=(a6*a106);
  a10=(a10+a93);
  if (res[0]!=0) res[0][3]=a10;
  a46=(a36*a46);
  a82=(a81*a82);
  a46=(a46+a82);
  a61=(a88*a61);
  a46=(a46+a61);
  a26=(a95*a26);
  a46=(a46+a26);
  a39=(a69*a39);
  a46=(a46-a39);
  a104=(a46/a104);
  a106=(a104*a106);
  a14=(a14+a106);
  if (res[0]!=0) res[0][4]=a14;
  a14=(a53*a48);
  a106=(a77*a54);
  a14=(a14+a106);
  a106=(a84*a63);
  a14=(a14+a106);
  a106=(a91*a21);
  a14=(a14+a106);
  a106=(a73*a30);
  a14=(a14-a106);
  a106=arg[4]? arg[4][0] : 0;
  a14=(a14+a106);
  a106=(a37*a48);
  a39=(a100*a54);
  a106=(a106+a39);
  a39=(a101*a63);
  a106=(a106+a39);
  a39=(a102*a21);
  a106=(a106+a39);
  a39=(a103*a30);
  a106=(a106-a39);
  a39=(a105*a106);
  a14=(a14-a39);
  if (res[1]!=0) res[1][0]=a14;
  a45=(a45-a7);
  a7=(a45*a106);
  if (res[1]!=0) res[1][1]=a7;
  a7=(a52*a48);
  a14=(a76*a54);
  a7=(a7+a14);
  a14=(a83*a63);
  a7=(a7+a14);
  a14=(a90*a21);
  a7=(a7+a14);
  a14=(a42*a30);
  a7=(a7-a14);
  a14=(a68*a106);
  a7=(a7-a14);
  if (res[1]!=0) res[1][2]=a7;
  a7=(a32*a48);
  a14=(a80*a54);
  a7=(a7+a14);
  a14=(a87*a63);
  a7=(a7+a14);
  a14=(a94*a21);
  a7=(a7+a14);
  a14=(a70*a30);
  a7=(a7-a14);
  a14=(a6*a106);
  a7=(a7-a14);
  if (res[1]!=0) res[1][3]=a7;
  a48=(a36*a48);
  a54=(a81*a54);
  a48=(a48+a54);
  a63=(a88*a63);
  a48=(a48+a63);
  a21=(a95*a21);
  a48=(a48+a21);
  a30=(a69*a30);
  a48=(a48-a30);
  a106=(a104*a106);
  a48=(a48-a106);
  if (res[1]!=0) res[1][4]=a48;
  a48=(a105*a99);
  a75=(a75-a48);
  if (res[1]!=0) res[1][5]=a75;
  a75=(a45*a99);
  if (res[1]!=0) res[1][6]=a75;
  a75=(a68*a99);
  a15=(a15-a75);
  if (res[1]!=0) res[1][7]=a15;
  a15=(a6*a99);
  a5=(a5-a15);
  if (res[1]!=0) res[1][8]=a5;
  a99=(a104*a99);
  a46=(a46-a99);
  if (res[1]!=0) res[1][9]=a46;
  a53=(a53*a12);
  a77=(a77*a57);
  a53=(a53+a77);
  a84=(a84*a89);
  a53=(a53+a84);
  a84=(a91*a16);
  a53=(a53+a84);
  a84=(a73*a1);
  a53=(a53-a84);
  a37=(a37*a12);
  a100=(a100*a57);
  a37=(a37+a100);
  a101=(a101*a89);
  a37=(a37+a101);
  a101=(a102*a16);
  a37=(a37+a101);
  a101=(a103*a1);
  a37=(a37-a101);
  a101=(a105*a37);
  a53=(a53-a101);
  if (res[1]!=0) res[1][10]=a53;
  a53=(a45*a37);
  if (res[1]!=0) res[1][11]=a53;
  a52=(a52*a12);
  a76=(a76*a57);
  a52=(a52+a76);
  a83=(a83*a89);
  a52=(a52+a83);
  a83=(a90*a16);
  a52=(a52+a83);
  a83=(a42*a1);
  a52=(a52-a83);
  a83=arg[6]? arg[6][0] : 0;
  a52=(a52+a83);
  a83=(a68*a37);
  a52=(a52-a83);
  if (res[1]!=0) res[1][12]=a52;
  a32=(a32*a12);
  a80=(a80*a57);
  a32=(a32+a80);
  a87=(a87*a89);
  a32=(a32+a87);
  a87=(a94*a16);
  a32=(a32+a87);
  a87=(a70*a1);
  a32=(a32-a87);
  a87=(a6*a37);
  a32=(a32-a87);
  if (res[1]!=0) res[1][13]=a32;
  a36=(a36*a12);
  a81=(a81*a57);
  a36=(a36+a81);
  a88=(a88*a89);
  a36=(a36+a88);
  a16=(a95*a16);
  a36=(a36+a16);
  a1=(a69*a1);
  a36=(a36-a1);
  a37=(a104*a37);
  a36=(a36-a37);
  if (res[1]!=0) res[1][14]=a36;
  a36=(a105*a102);
  a91=(a91-a36);
  if (res[1]!=0) res[1][15]=a91;
  a91=(a45*a102);
  if (res[1]!=0) res[1][16]=a91;
  a91=(a68*a102);
  a90=(a90-a91);
  if (res[1]!=0) res[1][17]=a90;
  a90=arg[7]? arg[7][0] : 0;
  a94=(a94+a90);
  a90=(a6*a102);
  a94=(a94-a90);
  if (res[1]!=0) res[1][18]=a94;
  a102=(a104*a102);
  a95=(a95-a102);
  if (res[1]!=0) res[1][19]=a95;
  a105=(a105*a103);
  a73=(a73-a105);
  if (res[1]!=0) res[1][20]=a73;
  a45=(a45*a103);
  if (res[1]!=0) res[1][21]=a45;
  a68=(a68*a103);
  a42=(a42-a68);
  if (res[1]!=0) res[1][22]=a42;
  a6=(a6*a103);
  a70=(a70-a6);
  if (res[1]!=0) res[1][23]=a70;
  a70=arg[8]? arg[8][0] : 0;
  a69=(a69+a70);
  a104=(a104*a103);
  a69=(a69-a104);
  if (res[1]!=0) res[1][24]=a69;
  return 0;
}

CASADI_SYMBOL_EXPORT int EKF_Func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int EKF_Func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int EKF_Func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void EKF_Func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int EKF_Func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void EKF_Func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void EKF_Func_incref(void) {
}

CASADI_SYMBOL_EXPORT void EKF_Func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int EKF_Func_n_in(void) { return 10;}

CASADI_SYMBOL_EXPORT casadi_int EKF_Func_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real EKF_Func_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* EKF_Func_name_in(casadi_int i){
  switch (i) {
    case 0: return "u";
    case 1: return "y";
    case 2: return "xhatp";
    case 3: return "Pkp";
    case 4: return "Q11";
    case 5: return "Q22";
    case 6: return "Q33";
    case 7: return "Q44";
    case 8: return "Q55";
    case 9: return "R";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* EKF_Func_name_out(casadi_int i){
  switch (i) {
    case 0: return "xhat";
    case 1: return "Phat";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* EKF_Func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* EKF_Func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int EKF_Func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
