/* This file was automatically generated by pyNLControl.*/


#include "EKF_Code.h"
#include "EKF_Code_Call.h"

void EKF_Code_Call_Func(casadi_real *u, casadi_real *y, casadi_real *xhatp, casadi_real *Pkp, casadi_real *Q11, casadi_real *Q22, casadi_real *Q33, casadi_real *Q44, casadi_real *Q55, casadi_real *R, casadi_real *xhat,  casadi_real *Phat )
{
    int i;

    const casadi_real *arg[10];
    casadi_real *res[2];
    casadi_int iw[0];
    casadi_real w[68];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 1;
    
    
    arg[2] = w + 2;
    
    
    arg[3] = w + 7;
    
    
    arg[4] = w + 32;
    
    
    arg[5] = w + 33;
    
    
    arg[6] = w + 34;
    
    
    arg[7] = w + 35;
    
    
    arg[8] = w + 36;
    
    
    arg[9] = w + 37;
    
    
    
    
    
    
    res[0] = w + 38;
    
    
    res[1] = w + 43;
    
    
    
    
    
    for (i = 0; i < 1; i++)
        w[i] = u[i-0];
    
    
    for (i = 1; i < 2; i++)
        w[i] = y[i-1];
    
    
    for (i = 2; i < 7; i++)
        w[i] = xhatp[i-2];
    
    
    for (i = 7; i < 32; i++)
        w[i] = Pkp[i-7];
    
    
    for (i = 32; i < 33; i++)
        w[i] = Q11[i-32];
    
    
    for (i = 33; i < 34; i++)
        w[i] = Q22[i-33];
    
    
    for (i = 34; i < 35; i++)
        w[i] = Q33[i-34];
    
    
    for (i = 35; i < 36; i++)
        w[i] = Q44[i-35];
    
    
    for (i = 36; i < 37; i++)
        w[i] = Q55[i-36];
    
    
    for (i = 37; i < 38; i++)
        w[i] = R[i-37];
    
    
    EKF_Func (arg, res, iw, w + 68, 0);
    
    
    
    for (i = 38; i < 43; i++)
        xhat[i-38] = w[i];
    
    
    for (i = 43; i < 68; i++)
        Phat[i-43] = w[i];
    
    
}