/* This file was automatically generated by pyNLControl.*/


#include "MHEArrival.h"

void MHEArrival_Call_Func(casadi_real *xL, casadi_real *pL, casadi_real *xLb, casadi_real *pLb, casadi_real *PL, casadi_real *uL, casadi_real *yL, casadi_real *VL, casadi_real *WL, casadi_real *Wp, casadi_real *zGuess, casadi_real *um, casadi_real *ym, casadi_real *zOp, casadi_real *xLbn,  casadi_real *pLbn,  casadi_real *PLn,  casadi_real *zOut,  casadi_real *p_hat,  casadi_real *x_hat,  casadi_real *Cost,  casadi_real *xLout );