/* This file was automatically generated by pyNLControl.*/


#include "MHEArrival.h"
#include "MHEArrival_Call.h"

void MHEArrival_Call_Func(casadi_real *xL, casadi_real *pL, casadi_real *xLb, casadi_real *pLb, casadi_real *PL, casadi_real *uL, casadi_real *yL, casadi_real *VL, casadi_real *WL, casadi_real *Wp, casadi_real *zGuess, casadi_real *um, casadi_real *ym, casadi_real *zOp, casadi_real *xLbn,  casadi_real *pLbn,  casadi_real *PLn,  casadi_real *zOut,  casadi_real *p_hat,  casadi_real *x_hat,  casadi_real *Cost,  casadi_real *xLout )
{
    int i;

    const casadi_real *arg[43];
    casadi_real *res[23];
    casadi_int iw[185];
    casadi_real w[216];

    
    
    
    
    arg[0] = w + 0;
    
    
    arg[1] = w + 3;
    
    
    arg[2] = w + 5;
    
    
    arg[3] = w + 8;
    
    
    arg[4] = w + 10;
    
    
    arg[5] = w + 35;
    
    
    arg[6] = w + 36;
    
    
    arg[7] = w + 37;
    
    
    arg[8] = w + 38;
    
    
    arg[9] = w + 47;
    
    
    arg[10] = w + 51;
    
    
    arg[11] = w + 86;
    
    
    arg[12] = w + 96;
    
    
    arg[13] = w + 107;
    
    
    
    
    
    
    res[0] = w + 142;
    
    
    res[1] = w + 145;
    
    
    res[2] = w + 147;
    
    
    res[3] = w + 172;
    
    
    res[4] = w + 207;
    
    
    res[5] = w + 209;
    
    
    res[6] = w + 212;
    
    
    res[7] = w + 213;
    
    
    
    
    
    for (i = 0; i < 3; i++)
        w[i] = xL[i-0];
    
    
    for (i = 3; i < 5; i++)
        w[i] = pL[i-3];
    
    
    for (i = 5; i < 8; i++)
        w[i] = xLb[i-5];
    
    
    for (i = 8; i < 10; i++)
        w[i] = pLb[i-8];
    
    
    for (i = 10; i < 35; i++)
        w[i] = PL[i-10];
    
    
    for (i = 35; i < 36; i++)
        w[i] = uL[i-35];
    
    
    for (i = 36; i < 37; i++)
        w[i] = yL[i-36];
    
    
    for (i = 37; i < 38; i++)
        w[i] = VL[i-37];
    
    
    for (i = 38; i < 47; i++)
        w[i] = WL[i-38];
    
    
    for (i = 47; i < 51; i++)
        w[i] = Wp[i-47];
    
    
    for (i = 51; i < 86; i++)
        w[i] = zGuess[i-51];
    
    
    for (i = 86; i < 96; i++)
        w[i] = um[i-86];
    
    
    for (i = 96; i < 107; i++)
        w[i] = ym[i-96];
    
    
    for (i = 107; i < 142; i++)
        w[i] = zOp[i-107];
    
    
    ArrivalMHE (arg, res, iw, w + 216, 0);
    
    
    
    for (i = 142; i < 145; i++)
        xLbn[i-142] = w[i];
    
    
    for (i = 145; i < 147; i++)
        pLbn[i-145] = w[i];
    
    
    for (i = 147; i < 172; i++)
        PLn[i-147] = w[i];
    
    
    for (i = 172; i < 207; i++)
        zOut[i-172] = w[i];
    
    
    for (i = 207; i < 209; i++)
        p_hat[i-207] = w[i];
    
    
    for (i = 209; i < 212; i++)
        x_hat[i-209] = w[i];
    
    
    for (i = 212; i < 213; i++)
        Cost[i-212] = w[i];
    
    
    for (i = 213; i < 216; i++)
        xLout[i-213] = w[i];
    
    
}